### ISSUE TITLE
BUG: Error page when clicking "Login to Bookmark this Event"

### ISSUE THREAD

**Issue by Shamitbh** [gcivil-nyu-org/INET-Team-3-F2022#107]
-When not logged in, if I go to the “Browse Events” tab and view the Public Events and click on “Login to Bookmark this event” under one of the events, I am led to an error page (See screenshot below)
![Screen Shot 2022-11-26 at 1 40 51 PM](https://user-images.githubusercontent.com/24572815/204110198-4a03e79d-f973-45b6-b502-6c953c214a45.png)

**Comment by matthewgabriele94** [comment]
Thanks for catching! We had been redirecting to an outdated URL path, but we've since fixed the problem. The User is now redirected to the login page instead of an error page.
