### ISSUE TITLE
Login to Bookmark this event give a 404 page

### ISSUE THREAD

**Issue by Rtlyc** [gcivil-nyu-org/INET-Team-3-F2022#96]
https://user-images.githubusercontent.com/49352204/203441621-270651a6-f780-470c-9352-6d7faa01feb1.mov

**Comment by matthewgabriele94** [comment]
Thanks for catching! We had been redirecting to an outdated URL path, but we've since fixed the problem. The User is now redirected to the login page instead of an error page.
